//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Commercial.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int tel { get; set; }
        public Nullable<int> utilisateur_id { get; set; }
        public Nullable<int> commande_id { get; set; }
    
        public virtual commande commande { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
