//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Commercial.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorie
    {
        public int id { get; set; }
        public string libelle { get; set; }
        public Nullable<int> article_id { get; set; }
    
        public virtual article article { get; set; }
    }
}
